version: "3.9"

services:
  fastapi_app:
    container_name: fastapi_app
    image: sorxill/tracker:test_base
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
    build: .

  fastapi_db:
    container_name: fastapi_db
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
