"""create tasks_collaborators table

Revision ID: 2ad9b9971266
Revises: 2cf22df6d5f8
Create Date: 2024-02-02 11:53:24.021387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad9b9971266'
down_revision: Union[str, None] = '2cf22df6d5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('collaborators_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collaborators_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('tasks', 'collaborators')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('collaborators', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_table('tasks_collaborators')
    # ### end Alembic commands ###
