"""update_models

Revision ID: 2cb061bd0acc
Revises: 65f325cd89b5
Create Date: 2024-01-27 19:14:02.670948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb061bd0acc'
down_revision: Union[str, None] = '65f325cd89b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('task_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_status')
    op.drop_column('projects_users', 'is_active')
    # ### end Alembic commands ###
