name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    linter:
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.10.12]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: true

            - name: Install dependencies
              run: |
                poetry config virtualenvs.in-project true
                poetry self add 'poethepoet[poetry_plugin]'
                poetry install --no-interaction
            - name: Run linter
              run: poetry poe lint

